// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


enum NativeCaptureStatus {
  ok,
  skippedByDHash,
  unsupportedApi,
  unsupportedRenderMode,
  surfaceUnavailable,
  timeout,
  pixelCopyFailed,
  processingFailed,
  cancelled,
  disposed,
}

enum NativeCaptureCoverage {
  engineSurface,
  windowComposite,
  viewHierarchy,
}

enum NativeCaptureRenderMode {
  surfaceView,
  textureView,
  hybrid,
  unknown,
}

class NativeCaptureMask {
  NativeCaptureMask({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  double x;

  double y;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[
      x,
      y,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCaptureMask decode(Object result) {
    result as List<Object?>;
    return NativeCaptureMask(
      x: result[0]! as double,
      y: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCaptureMask || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeCaptureTimings {
  NativeCaptureTimings({
    required this.surfaceCopyMicros,
    required this.maskFillMicros,
    required this.dHashMicros,
    required this.jpegMicros,
    required this.sha256Micros,
    required this.pixelReadbackMicros,
  });

  int surfaceCopyMicros;

  int maskFillMicros;

  int dHashMicros;

  int jpegMicros;

  int sha256Micros;

  int pixelReadbackMicros;

  List<Object?> _toList() {
    return <Object?>[
      surfaceCopyMicros,
      maskFillMicros,
      dHashMicros,
      jpegMicros,
      sha256Micros,
      pixelReadbackMicros,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCaptureTimings decode(Object result) {
    result as List<Object?>;
    return NativeCaptureTimings(
      surfaceCopyMicros: result[0]! as int,
      maskFillMicros: result[1]! as int,
      dHashMicros: result[2]! as int,
      jpegMicros: result[3]! as int,
      sha256Micros: result[4]! as int,
      pixelReadbackMicros: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCaptureTimings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeCaptureCapabilities {
  NativeCaptureCapabilities({
    required this.nativeCaptureSupported,
    required this.apiLevel,
    required this.minNativeApi,
  });

  bool nativeCaptureSupported;

  int apiLevel;

  int minNativeApi;

  List<Object?> _toList() {
    return <Object?>[
      nativeCaptureSupported,
      apiLevel,
      minNativeApi,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCaptureCapabilities decode(Object result) {
    result as List<Object?>;
    return NativeCaptureCapabilities(
      nativeCaptureSupported: result[0]! as bool,
      apiLevel: result[1]! as int,
      minNativeApi: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCaptureCapabilities || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeCaptureRequest {
  NativeCaptureRequest({
    required this.requestId,
    required this.pixelWidth,
    required this.pixelHeight,
    required this.force,
    required this.lastDHash,
    required this.masks,
  });

  int requestId;

  int pixelWidth;

  int pixelHeight;

  bool force;

  String lastDHash;

  List<NativeCaptureMask> masks;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      pixelWidth,
      pixelHeight,
      force,
      lastDHash,
      masks,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCaptureRequest decode(Object result) {
    result as List<Object?>;
    return NativeCaptureRequest(
      requestId: result[0]! as int,
      pixelWidth: result[1]! as int,
      pixelHeight: result[2]! as int,
      force: result[3]! as bool,
      lastDHash: result[4]! as String,
      masks: (result[5] as List<Object?>?)!.cast<NativeCaptureMask>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCaptureRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class NativeCaptureResult {
  NativeCaptureResult({
    required this.requestId,
    required this.status,
    this.coverage,
    required this.jpeg,
    required this.width,
    required this.height,
    required this.dHash,
    required this.contentHash,
    required this.timings,
    required this.renderMode,
    required this.incomplete,
  });

  int requestId;

  NativeCaptureStatus status;

  NativeCaptureCoverage? coverage;

  Uint8List jpeg;

  int width;

  int height;

  String dHash;

  String contentHash;

  NativeCaptureTimings timings;

  NativeCaptureRenderMode renderMode;

  bool incomplete;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      status,
      coverage,
      jpeg,
      width,
      height,
      dHash,
      contentHash,
      timings,
      renderMode,
      incomplete,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCaptureResult decode(Object result) {
    result as List<Object?>;
    return NativeCaptureResult(
      requestId: result[0]! as int,
      status: result[1]! as NativeCaptureStatus,
      coverage: result[2] as NativeCaptureCoverage?,
      jpeg: result[3]! as Uint8List,
      width: result[4]! as int,
      height: result[5]! as int,
      dHash: result[6]! as String,
      contentHash: result[7]! as String,
      timings: result[8]! as NativeCaptureTimings,
      renderMode: result[9]! as NativeCaptureRenderMode,
      incomplete: result[10]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCaptureResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeCaptureStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is NativeCaptureCoverage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is NativeCaptureRenderMode) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is NativeCaptureMask) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is NativeCaptureTimings) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is NativeCaptureCapabilities) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is NativeCaptureRequest) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is NativeCaptureResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NativeCaptureStatus.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NativeCaptureCoverage.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NativeCaptureRenderMode.values[value];
      case 132: 
        return NativeCaptureMask.decode(readValue(buffer)!);
      case 133: 
        return NativeCaptureTimings.decode(readValue(buffer)!);
      case 134: 
        return NativeCaptureCapabilities.decode(readValue(buffer)!);
      case 135: 
        return NativeCaptureRequest.decode(readValue(buffer)!);
      case 136: 
        return NativeCaptureResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeCaptureHostApi {
  /// Constructor for [NativeCaptureHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeCaptureHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeCaptureCapabilities> getCapabilities() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tugboat.NativeCaptureHostApi.getCapabilities$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NativeCaptureCapabilities?)!;
    }
  }

  Future<NativeCaptureResult> capture(NativeCaptureRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tugboat.NativeCaptureHostApi.capture$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NativeCaptureResult?)!;
    }
  }

  Future<void> cancel(int requestId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tugboat.NativeCaptureHostApi.cancel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> dispose() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tugboat.NativeCaptureHostApi.dispose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
