// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsNativeCapture(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsNativeCapture(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsNativeCapture(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashNativeCapture(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashNativeCapture(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashNativeCapture(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum NativeCaptureStatus: Int {
  case ok = 0
  case skippedByDHash = 1
  case unsupportedApi = 2
  case unsupportedRenderMode = 3
  case surfaceUnavailable = 4
  case timeout = 5
  case pixelCopyFailed = 6
  case processingFailed = 7
  case cancelled = 8
  case disposed = 9
}

enum NativeCaptureCoverage: Int {
  case engineSurface = 0
  case windowComposite = 1
  case viewHierarchy = 2
}

enum NativeCaptureRenderMode: Int {
  case surfaceView = 0
  case textureView = 1
  case hybrid = 2
  case unknown = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeCaptureMask: Hashable {
  var x: Double
  var y: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCaptureMask? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return NativeCaptureMask(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
  static func == (lhs: NativeCaptureMask, rhs: NativeCaptureMask) -> Bool {
    return deepEqualsNativeCapture(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashNativeCapture(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeCaptureTimings: Hashable {
  var surfaceCopyMicros: Int64
  var maskFillMicros: Int64
  var dHashMicros: Int64
  var jpegMicros: Int64
  var sha256Micros: Int64
  var pixelReadbackMicros: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCaptureTimings? {
    let surfaceCopyMicros = pigeonVar_list[0] as! Int64
    let maskFillMicros = pigeonVar_list[1] as! Int64
    let dHashMicros = pigeonVar_list[2] as! Int64
    let jpegMicros = pigeonVar_list[3] as! Int64
    let sha256Micros = pigeonVar_list[4] as! Int64
    let pixelReadbackMicros = pigeonVar_list[5] as! Int64

    return NativeCaptureTimings(
      surfaceCopyMicros: surfaceCopyMicros,
      maskFillMicros: maskFillMicros,
      dHashMicros: dHashMicros,
      jpegMicros: jpegMicros,
      sha256Micros: sha256Micros,
      pixelReadbackMicros: pixelReadbackMicros
    )
  }
  func toList() -> [Any?] {
    return [
      surfaceCopyMicros,
      maskFillMicros,
      dHashMicros,
      jpegMicros,
      sha256Micros,
      pixelReadbackMicros,
    ]
  }
  static func == (lhs: NativeCaptureTimings, rhs: NativeCaptureTimings) -> Bool {
    return deepEqualsNativeCapture(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashNativeCapture(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeCaptureCapabilities: Hashable {
  var nativeCaptureSupported: Bool
  var apiLevel: Int64
  var minNativeApi: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCaptureCapabilities? {
    let nativeCaptureSupported = pigeonVar_list[0] as! Bool
    let apiLevel = pigeonVar_list[1] as! Int64
    let minNativeApi = pigeonVar_list[2] as! Int64

    return NativeCaptureCapabilities(
      nativeCaptureSupported: nativeCaptureSupported,
      apiLevel: apiLevel,
      minNativeApi: minNativeApi
    )
  }
  func toList() -> [Any?] {
    return [
      nativeCaptureSupported,
      apiLevel,
      minNativeApi,
    ]
  }
  static func == (lhs: NativeCaptureCapabilities, rhs: NativeCaptureCapabilities) -> Bool {
    return deepEqualsNativeCapture(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashNativeCapture(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeCaptureRequest: Hashable {
  var requestId: Int64
  var pixelWidth: Int64
  var pixelHeight: Int64
  var force: Bool
  var lastDHash: String
  var masks: [NativeCaptureMask]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCaptureRequest? {
    let requestId = pigeonVar_list[0] as! Int64
    let pixelWidth = pigeonVar_list[1] as! Int64
    let pixelHeight = pigeonVar_list[2] as! Int64
    let force = pigeonVar_list[3] as! Bool
    let lastDHash = pigeonVar_list[4] as! String
    let masks = pigeonVar_list[5] as! [NativeCaptureMask]

    return NativeCaptureRequest(
      requestId: requestId,
      pixelWidth: pixelWidth,
      pixelHeight: pixelHeight,
      force: force,
      lastDHash: lastDHash,
      masks: masks
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      pixelWidth,
      pixelHeight,
      force,
      lastDHash,
      masks,
    ]
  }
  static func == (lhs: NativeCaptureRequest, rhs: NativeCaptureRequest) -> Bool {
    return deepEqualsNativeCapture(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashNativeCapture(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeCaptureResult: Hashable {
  var requestId: Int64
  var status: NativeCaptureStatus
  var coverage: NativeCaptureCoverage? = nil
  var jpeg: FlutterStandardTypedData
  var width: Int64
  var height: Int64
  var dHash: String
  var contentHash: String
  var timings: NativeCaptureTimings
  var renderMode: NativeCaptureRenderMode
  var incomplete: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCaptureResult? {
    let requestId = pigeonVar_list[0] as! Int64
    let status = pigeonVar_list[1] as! NativeCaptureStatus
    let coverage: NativeCaptureCoverage? = nilOrValue(pigeonVar_list[2])
    let jpeg = pigeonVar_list[3] as! FlutterStandardTypedData
    let width = pigeonVar_list[4] as! Int64
    let height = pigeonVar_list[5] as! Int64
    let dHash = pigeonVar_list[6] as! String
    let contentHash = pigeonVar_list[7] as! String
    let timings = pigeonVar_list[8] as! NativeCaptureTimings
    let renderMode = pigeonVar_list[9] as! NativeCaptureRenderMode
    let incomplete = pigeonVar_list[10] as! Bool

    return NativeCaptureResult(
      requestId: requestId,
      status: status,
      coverage: coverage,
      jpeg: jpeg,
      width: width,
      height: height,
      dHash: dHash,
      contentHash: contentHash,
      timings: timings,
      renderMode: renderMode,
      incomplete: incomplete
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      status,
      coverage,
      jpeg,
      width,
      height,
      dHash,
      contentHash,
      timings,
      renderMode,
      incomplete,
    ]
  }
  static func == (lhs: NativeCaptureResult, rhs: NativeCaptureResult) -> Bool {
    return deepEqualsNativeCapture(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashNativeCapture(value: toList(), hasher: &hasher)
  }
}

private class NativeCapturePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeCaptureStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeCaptureCoverage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeCaptureRenderMode(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return NativeCaptureMask.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeCaptureTimings.fromList(self.readValue() as! [Any?])
    case 134:
      return NativeCaptureCapabilities.fromList(self.readValue() as! [Any?])
    case 135:
      return NativeCaptureRequest.fromList(self.readValue() as! [Any?])
    case 136:
      return NativeCaptureResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NativeCapturePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeCaptureStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeCaptureCoverage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeCaptureRenderMode {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeCaptureMask {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCaptureTimings {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCaptureCapabilities {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCaptureRequest {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCaptureResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NativeCapturePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeCapturePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeCapturePigeonCodecWriter(data: data)
  }
}

class NativeCapturePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeCapturePigeonCodec(readerWriter: NativeCapturePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeCaptureHostApi {
  func getCapabilities() throws -> NativeCaptureCapabilities
  func capture(request: NativeCaptureRequest, completion: @escaping (Result<NativeCaptureResult, Error>) -> Void)
  func cancel(requestId: Int64) throws
  func dispose() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeCaptureHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeCapturePigeonCodec.shared }
  /// Sets up an instance of `NativeCaptureHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeCaptureHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tugboat.NativeCaptureHostApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCapabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    let captureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tugboat.NativeCaptureHostApi.capture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      captureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeCaptureRequest
        api.capture(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      captureChannel.setMessageHandler(nil)
    }
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tugboat.NativeCaptureHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        do {
          try api.cancel(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tugboat.NativeCaptureHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
