// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.tugboat.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeCapturePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class NativeCaptureStatus(val raw: Int) {
  OK(0),
  SKIPPED_BY_DHASH(1),
  UNSUPPORTED_API(2),
  UNSUPPORTED_RENDER_MODE(3),
  SURFACE_UNAVAILABLE(4),
  TIMEOUT(5),
  PIXEL_COPY_FAILED(6),
  PROCESSING_FAILED(7),
  CANCELLED(8),
  DISPOSED(9);

  companion object {
    fun ofRaw(raw: Int): NativeCaptureStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeCaptureCoverage(val raw: Int) {
  ENGINE_SURFACE(0),
  WINDOW_COMPOSITE(1),
  VIEW_HIERARCHY(2);

  companion object {
    fun ofRaw(raw: Int): NativeCaptureCoverage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeCaptureRenderMode(val raw: Int) {
  SURFACE_VIEW(0),
  TEXTURE_VIEW(1),
  HYBRID(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): NativeCaptureRenderMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCaptureMask (
  val x: Double,
  val y: Double,
  val width: Double,
  val height: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCaptureMask {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      val width = pigeonVar_list[2] as Double
      val height = pigeonVar_list[3] as Double
      return NativeCaptureMask(x, y, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeCaptureMask) {
      return false
    }
    if (this === other) {
      return true
    }
    return NativeCapturePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCaptureTimings (
  val surfaceCopyMicros: Long,
  val maskFillMicros: Long,
  val dHashMicros: Long,
  val jpegMicros: Long,
  val sha256Micros: Long,
  val pixelReadbackMicros: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCaptureTimings {
      val surfaceCopyMicros = pigeonVar_list[0] as Long
      val maskFillMicros = pigeonVar_list[1] as Long
      val dHashMicros = pigeonVar_list[2] as Long
      val jpegMicros = pigeonVar_list[3] as Long
      val sha256Micros = pigeonVar_list[4] as Long
      val pixelReadbackMicros = pigeonVar_list[5] as Long
      return NativeCaptureTimings(surfaceCopyMicros, maskFillMicros, dHashMicros, jpegMicros, sha256Micros, pixelReadbackMicros)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      surfaceCopyMicros,
      maskFillMicros,
      dHashMicros,
      jpegMicros,
      sha256Micros,
      pixelReadbackMicros,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeCaptureTimings) {
      return false
    }
    if (this === other) {
      return true
    }
    return NativeCapturePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCaptureCapabilities (
  val nativeCaptureSupported: Boolean,
  val apiLevel: Long,
  val minNativeApi: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCaptureCapabilities {
      val nativeCaptureSupported = pigeonVar_list[0] as Boolean
      val apiLevel = pigeonVar_list[1] as Long
      val minNativeApi = pigeonVar_list[2] as Long
      return NativeCaptureCapabilities(nativeCaptureSupported, apiLevel, minNativeApi)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      nativeCaptureSupported,
      apiLevel,
      minNativeApi,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeCaptureCapabilities) {
      return false
    }
    if (this === other) {
      return true
    }
    return NativeCapturePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCaptureRequest (
  val requestId: Long,
  val pixelWidth: Long,
  val pixelHeight: Long,
  val force: Boolean,
  val lastDHash: String,
  val masks: List<NativeCaptureMask>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCaptureRequest {
      val requestId = pigeonVar_list[0] as Long
      val pixelWidth = pigeonVar_list[1] as Long
      val pixelHeight = pigeonVar_list[2] as Long
      val force = pigeonVar_list[3] as Boolean
      val lastDHash = pigeonVar_list[4] as String
      val masks = pigeonVar_list[5] as List<NativeCaptureMask>
      return NativeCaptureRequest(requestId, pixelWidth, pixelHeight, force, lastDHash, masks)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      pixelWidth,
      pixelHeight,
      force,
      lastDHash,
      masks,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeCaptureRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return NativeCapturePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCaptureResult (
  val requestId: Long,
  val status: NativeCaptureStatus,
  val coverage: NativeCaptureCoverage? = null,
  val jpeg: ByteArray,
  val width: Long,
  val height: Long,
  val dHash: String,
  val contentHash: String,
  val timings: NativeCaptureTimings,
  val renderMode: NativeCaptureRenderMode,
  val incomplete: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCaptureResult {
      val requestId = pigeonVar_list[0] as Long
      val status = pigeonVar_list[1] as NativeCaptureStatus
      val coverage = pigeonVar_list[2] as NativeCaptureCoverage?
      val jpeg = pigeonVar_list[3] as ByteArray
      val width = pigeonVar_list[4] as Long
      val height = pigeonVar_list[5] as Long
      val dHash = pigeonVar_list[6] as String
      val contentHash = pigeonVar_list[7] as String
      val timings = pigeonVar_list[8] as NativeCaptureTimings
      val renderMode = pigeonVar_list[9] as NativeCaptureRenderMode
      val incomplete = pigeonVar_list[10] as Boolean
      return NativeCaptureResult(requestId, status, coverage, jpeg, width, height, dHash, contentHash, timings, renderMode, incomplete)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      status,
      coverage,
      jpeg,
      width,
      height,
      dHash,
      contentHash,
      timings,
      renderMode,
      incomplete,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeCaptureResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return NativeCapturePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class NativeCapturePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeCaptureStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeCaptureCoverage.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeCaptureRenderMode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCaptureMask.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCaptureTimings.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCaptureCapabilities.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCaptureRequest.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCaptureResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeCaptureStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NativeCaptureCoverage -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is NativeCaptureRenderMode -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is NativeCaptureMask -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeCaptureTimings -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeCaptureCapabilities -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NativeCaptureRequest -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NativeCaptureResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeCaptureHostApi {
  fun getCapabilities(): NativeCaptureCapabilities
  fun capture(request: NativeCaptureRequest, callback: (Result<NativeCaptureResult>) -> Unit)
  fun cancel(requestId: Long)
  fun dispose()

  companion object {
    /** The codec used by NativeCaptureHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeCapturePigeonCodec()
    }
    /** Sets up an instance of `NativeCaptureHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeCaptureHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tugboat.NativeCaptureHostApi.getCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCapabilities())
            } catch (exception: Throwable) {
              NativeCapturePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tugboat.NativeCaptureHostApi.capture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeCaptureRequest
            api.capture(requestArg) { result: Result<NativeCaptureResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeCapturePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeCapturePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tugboat.NativeCaptureHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancel(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeCapturePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tugboat.NativeCaptureHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              NativeCapturePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
